#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bmap-tools
Version  : 3.6
Release  : 26
URL      : https://github.com/intel/bmap-tools/archive/v3.6/bmap-tools-3.6.tar.gz
Source0  : https://github.com/intel/bmap-tools/archive/v3.6/bmap-tools-3.6.tar.gz
Summary  : Tools to generate block map (AKA bmap) and flash images using bmap
Group    : Development/Tools
License  : GPL-2.0
Requires: bmap-tools-bin = %{version}-%{release}
Requires: bmap-tools-license = %{version}-%{release}
Requires: bmap-tools-python = %{version}-%{release}
Requires: bmap-tools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Tools to generate block map (AKA bmap) and flash images using bmap. Bmaptool is
a generic tool for creating the block map (bmap) for a file, and copying files
using the block map. The idea is that large file containing unused blocks, like
raw system image files, can be copied or flashed a lot faster with bmaptool
than with traditional tools like "dd" or "cp". See
source.tizen.org/documentation/reference/bmaptool for more information.

%package bin
Summary: bin components for the bmap-tools package.
Group: Binaries
Requires: bmap-tools-license = %{version}-%{release}

%description bin
bin components for the bmap-tools package.


%package license
Summary: license components for the bmap-tools package.
Group: Default

%description license
license components for the bmap-tools package.


%package python
Summary: python components for the bmap-tools package.
Group: Default
Requires: bmap-tools-python3 = %{version}-%{release}

%description python
python components for the bmap-tools package.


%package python3
Summary: python3 components for the bmap-tools package.
Group: Default
Requires: python3-core

%description python3
python3 components for the bmap-tools package.


%prep
%setup -q -n bmap-tools-3.6
cd %{_builddir}/bmap-tools-3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1613614968
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bmap-tools
cp %{_builddir}/bmap-tools-3.6/COPYING %{buildroot}/usr/share/package-licenses/bmap-tools/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/bmap-tools-3.6/debian/copyright %{buildroot}/usr/share/package-licenses/bmap-tools/bf29a1eeb5e829b8596ed35b13d1ca42dfc9764d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bmaptool

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bmap-tools/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/bmap-tools/bf29a1eeb5e829b8596ed35b13d1ca42dfc9764d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
